package io.duo.sim.kernel.sut;

import io.duo.sim.kernel.api.ComponentException;
import io.duo.sim.kernel.api.Event;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

/**
 * external SUT 启动器（设计 §7.3，M6 交付物 1；决策 D7/D9 见 {@code docs/DECISIONS.md}）。
 *
 * <p><b>内核 → SUT 端点告知（主途径）</b>：生成端点配置文件（{@code launch.configOut}），
 * 写入 {@code duo.endpoint.<contract>=<endpoint>} 与节点 {@code config} 键值（{@code ready.*}
 * 是内核探针声明，不写入），并经环境变量 {@code duo.config} 把文件路径告知子进程。
 *
 * <p><b>SUT → 内核端点发现（兜底途径）</b>：解析子进程 stdout 中形如
 * {@code duo.endpoint.<contract>=<endpoint>} 的行（§7.3 行格式：**行首即前缀**，容忍首尾空白），
 * 记为「已发现端点」并发 {@code sim.external-endpoint} 事件（source=stdout）。
 * 注意：SUT 若把内核写入的配置行**原样回显**到 stdout，会被当作自身端点宣告——
 * 端点宣告行必须由 SUT 显式打印（设计约定）。
 *
 * <p><b>就绪</b>：轮询 {@link ReadyProbe}（tcp/http）至 {@code ready.timeout}；
 * 探针超时或 ready 前退出都归启动失败路径（§12），且**优先报「退出」根因**——
 * 进程已死时继续等探针超时会把根因掩盖成超时（与 in-process 的快速失败口径一致）。
 *
 * <p><b>生命周期归用户（§7.3）</b>：场景结束**不杀**进程（{@link #leftRunning()} 供调用方
 * 判定与提示，句柄经 {@link #process()} 暴露给用户自行终止）；但**启动失败**时销毁
 * （决策 D9：未就绪的子进程从未成为 SUT，留着必然泄漏）。
 */
public final class ExternalSutLauncher implements AutoCloseable {

    /** 探针轮询间隔。 */
    private static final long POLL_INTERVAL_MS = 200;
    /** 启动失败时等待子进程退出的宽限。 */
    private static final long KILL_TIMEOUT_MS = 5_000;
    /** 端点告知行的固定前缀（§7.3 行格式）。 */
    private static final String ENDPOINT_PREFIX = "duo.endpoint.";

    private final String sutId;
    private final List<String> command;
    private final Map<String, String> config;
    private final Map<String, String> endpoints;
    private final Consumer<Event> eventSink;
    private final Path configOut;
    private final ReadyProbe.Spec ready;
    private final Map<String, String> discovered = new ConcurrentHashMap<>();
    private final CountDownLatch exited = new CountDownLatch(1);
    /** stdout 读取线程（close() 需要先把它们从阻塞读里叫出来，见 close() 注释）。 */
    private final List<Thread> pumpThreads =
            java.util.Collections.synchronizedList(new ArrayList<>());
    private volatile Process process;
    private volatile boolean readyConfirmed;
    private volatile Integer exitCode;

    /**
     * @param command     空列表＝attach 形态（进程由用户自行启动，内核只写配置 + 探针就绪）
     * @param fallbackPort {@code ready.port} 缺省时的兜底端口（节点 exposes 首个非 0 端口）
     */
    public ExternalSutLauncher(String sutId, List<String> command, Map<String, String> config,
                               Map<String, String> endpoints, Consumer<Event> eventSink,
                               Path configOut, int fallbackPort) {
        this.sutId = sutId;
        this.command = List.copyOf(command);
        this.config = Map.copyOf(config);
        this.endpoints = Map.copyOf(endpoints);
        this.eventSink = eventSink;
        this.configOut = configOut;
        this.ready = ReadyProbe.spec(config, fallbackPort);
    }

    /**
     * 写端点配置文件 → （代起形态）拉起进程 → 轮询 ready。
     *
     * @throws ComponentException 探针超时 / ready 前退出 / 进程拉不起来
     */
    public void start() {
        writeConfigFile();
        if (!command.isEmpty()) {
            spawn();
        }
        try {
            awaitReady();
        } catch (RuntimeException e) {
            killProcess(); // D9：启动失败即销毁，不留孤儿 JVM
            throw e;
        }
        eventSink.accept(Event.sim("sim.external-sut-ready", sutId,
                Map.of("probe", ready.type(), "target", ready.describe(),
                        "attach", command.isEmpty())));
    }

    /** 端点配置文件内容（§7.3 主途径）：端点行 + 节点 config（剔除内核探针声明）。 */
    private void writeConfigFile() {
        if (configOut == null) {
            return;
        }
        try {
            if (configOut.getParent() != null) {
                Files.createDirectories(configOut.getParent());
            }
            try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(configOut,
                    StandardCharsets.UTF_8))) {
                pw.println("# generated by Duo — external SUT endpoint notification (§7.3)");
                endpoints.forEach((contract, addr) ->
                        pw.println(ENDPOINT_PREFIX + contract + "=" + addr));
                config.forEach((k, v) -> {
                    if (!k.startsWith("ready.")) {
                        pw.println(k + "=" + v);
                    }
                });
            }
        } catch (IOException e) {
            throw new ComponentException("cannot write external SUT config: " + configOut, e);
        }
    }

    private void spawn() {
        ProcessBuilder pb = new ProcessBuilder(command).redirectErrorStream(true);
        if (configOut != null) {
            pb.environment().put("duo.config", configOut.toAbsolutePath().toString());
        }
        try {
            process = pb.start();
        } catch (IOException e) {
            throw new ComponentException("cannot start external SUT process: "
                    + redactedCommand(), e);
        }
        eventSink.accept(Event.sim("sim.external-process-started", sutId,
                Map.of("pid", process.pid(), "command", redactedCommand())));
        Thread pump = Thread.ofVirtual().name("duo-external-stdout-" + sutId)
                .start(this::pumpStdout);
        pumpThreads.add(pump);
        Thread.ofVirtual().name("duo-external-exit-" + sutId).start(this::watchExit);
    }

    /** 事件载荷里 argv 的回显上限（安全审计 2026-09-20 复核 M-7）。 */
    public static final int MAX_ECHOED_ARGV_CHARS = 200;

    /**
     * 可安全回显的命令行（安全审计 2026-09-20 复核 M-7）。
     *
     * <p>审计期把**完整 argv**（{@code String.join(" ", command)}）写进
     * {@code sim.external-process-started} ⇒ 事件流 ⇒ {@code events.jsonl} ⇒ CI artifact：
     * 场景 YAML 里常见的 {@code --password=…}、{@code --token=…}、JDBC 连接串会整条外泄，
     * 而事件流是被上传、被回读、被 diff 的审查材料。
     *
     * <p>口径（"谁持有谁收摊"的同类推理）：**进程自己知道完整命令行，事件流不必要**。
     * 故只保留「可执行文件 + 参数个数 + 每个参数的安全摘要」：可执行文件按 basename 保留
     * （诊断上真正有用的是"起了什么"），参数一律不回显字面值，凭据形状的参数额外标注。
     */
    private String redactedCommand() {
        return commandForEvent(command);
    }

    /**
     * 命令行 → 可安全回显的摘要（{@code sim.external-process-started} 的载荷口径）。
     *
     * <p>包级可见是为了让回归用例**不启动进程**也能锁住这条口径——审计 M-7 的问题正是
     * "载荷里有什么"，不是"进程起没起"。
     */
    static String commandForEvent(List<String> command) {
        if (command.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append(basename(command.get(0))).append(" +")
                .append(command.size() - 1).append(" args");
        for (int i = 1; i < command.size(); i++) {
            sb.append(" | ").append(i).append(':').append(argDigest(command.get(i)));
        }
        String out = sb.toString();
        return out.length() > MAX_ECHOED_ARGV_CHARS
                ? out.substring(0, MAX_ECHOED_ARGV_CHARS) + "…" : out;
    }

    /** 单个参数的可回显形态：名字段保留、值段不回显；不像键值对的一律只给长度与指纹。 */
    private static String argDigest(String arg) {
        if (arg == null || arg.isEmpty()) {
            return "<empty>";
        }
        boolean looksLikeFlag = arg.startsWith("-");
        int eq = arg.indexOf('=');
        if (looksLikeFlag && eq > 0) {
            String name = arg.substring(0, eq);
            return isSecretName(name)
                    ? name + "=<redacted>" : name + "=<" + arg.length() + " chars>";
        }
        if (looksLikeFlag) {
            return arg; // 纯开关（--verbose 之类）不含值，回显本身不泄露
        }
        return "<" + arg.length() + " chars, fp " + fingerprint(arg) + ">";
    }

    /** 参数名是否指示凭据（命中即整值掩码，不回显长度/指纹）。 */
    private static boolean isSecretName(String name) {
        String n = name.toLowerCase(java.util.Locale.ROOT);
        return n.contains("pass") || n.contains("secret") || n.contains("token")
                || n.contains("key") || n.contains("credential") || n.contains("pwd");
    }

    /** 非凭据参数的内容指纹（同一参数值 ⇒ 同一指纹，可跨运行比对而不泄露内容）。 */
    private static String fingerprint(String value) {
        try {
            byte[] hash = java.security.MessageDigest.getInstance("SHA-256")
                    .digest(value.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder(8);
            for (int i = 0; i < 4; i++) {
                sb.append(String.format("%02x", hash[i]));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            return "?"; // SHA-256 是 JDK 必备算法；真缺失时宁可标注未知，也不回显原文
        }
    }

    private static String basename(String path) {
        String p = path.replace('\\', '/');
        int slash = p.lastIndexOf('/');
        return slash < 0 ? p : p.substring(slash + 1);
    }

    /** stdout 兜底途径：逐行找行首的 {@code duo.endpoint.<contract>=<endpoint>}（容忍首尾空白）。 */
    private void pumpStdout() {
        // 刻意**不**用 try-with-resources：句柄的释放归 close()（M-7），读线程只负责读。
        // 若这里也持有且在退出时关流，就会与 close() 抢同一把读锁——Windows 上阻塞读不响应
        // close()，两个线程会互相等到天荒地老（实测死锁）。一个 owner 管释放，这里只管读。
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(
                    process.getInputStream(), StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parsed = parseEndpointLine(line);
                if (parsed == null) {
                    continue;
                }
                discovered.put(parsed[0], parsed[1]);
                eventSink.accept(Event.sim("sim.external-endpoint", sutId,
                        Map.of("contract", parsed[0], "endpoint", parsed[1],
                                "source", "stdout")));
            }
        } catch (IOException ignored) {
            // 进程退出即流关闭：属正常收尾，不是错误
        }
    }

    /**
     * 解析端点告知行（包级可见供单测）：返回 {@code [contract, endpoint]}，非端点行返回 null。
     * 行格式严格按 §7.3——**行首**即 {@code duo.endpoint.}（容忍首尾空白），避免把日志中
     * 引用的配置文本误判为端点宣告。
     */
    static String[] parseEndpointLine(String line) {
        if (line == null) {
            return null;
        }
        String trimmed = line.trim();
        if (!trimmed.startsWith(ENDPOINT_PREFIX)) {
            return null;
        }
        int eq = trimmed.indexOf('=');
        if (eq < 0) {
            return null;
        }
        String contract = trimmed.substring(ENDPOINT_PREFIX.length(), eq).trim();
        String endpoint = trimmed.substring(eq + 1).trim();
        if (contract.isEmpty() || endpoint.isEmpty()) {
            return null;
        }
        return new String[]{contract, endpoint};
    }

    private void watchExit() {
        int code;
        try {
            code = process.waitFor();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return;
        }
        exitCode = code;
        exited.countDown();
        if (!readyConfirmed) {
            return; // ready 前退出由 start() 的竞速判定报根因，不在此发事实事件
        }
        if (code == 0) {
            eventSink.accept(Event.sut("sut.exited", sutId, Map.of("exitCode", code)));
        } else {
            eventSink.accept(Event.sut("sut.crashed", sutId, Map.of("exitCode", code,
                    "error", "external process exited with code " + code)));
        }
    }

    private void awaitReady() {
        long deadline = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(ready.timeoutMs());
        while (true) {
            Process p = process;
            if (p != null && !p.isAlive()) {
                throw new ComponentException("external SUT exited before ready: " + sutId
                        + " (exit code " + exitValueOf(p) + ")");
            }
            if (ReadyProbe.once(ready)) {
                readyConfirmed = true;
                return;
            }
            if (System.nanoTime() >= deadline) {
                throw new ComponentException("external SUT ready timeout (" + ready.timeoutMs()
                        + "ms): " + sutId + " (probe " + ready.type() + " " + ready.describe() + ")");
            }
            try {
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new ComponentException("external SUT ready interrupted: " + sutId, e);
            }
        }
    }

    private int exitValueOf(Process p) {
        try {
            return p.exitValue();
        } catch (IllegalThreadStateException e) {
            Integer seen = exitCode;
            return seen == null ? -1 : seen;
        }
    }

    /** 启动失败路径的销毁（D9）：先 destroy，宽限内不退再 destroyForcibly。 */
    private void killProcess() {
        Process p = process;
        if (p == null) {
            return;
        }
        if (p.isAlive()) {
            p.destroy();
            try {
                if (!p.waitFor(KILL_TIMEOUT_MS, TimeUnit.MILLISECONDS)) {
                    p.destroyForcibly();
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                p.destroyForcibly();
            }
        }
        exited.countDown();
    }

    // ---- 观测面 ----

    /** 场景结束时进程是否仍在运行（§7.3：内核不杀，由调用方提示用户自行终止）。 */
    public boolean leftRunning() {
        Process p = process;
        return p != null && p.isAlive();
    }

    /** 子进程句柄（attach 形态为 null）；生命周期归用户，故公开供其终止。 */
    public Process process() {
        return process;
    }

    /** 子进程 pid（attach 形态为 null）。 */
    public Long pid() {
        Process p = process;
        return p == null ? null : p.pid();
    }

    /** stdout 兜底途径发现的端点（contract → endpoint）。 */
    public Map<String, String> discoveredEndpoints() {
        return Map.copyOf(discovered);
    }

    /** ready 是否已被探针确认。 */
    public boolean readyConfirmed() {
        return readyConfirmed;
    }

    /** 退出码（未退出为 null）。 */
    public Integer exitCode() {
        return exitCode;
    }

    /** 等待退出（供诊断/测试）。 */
    public boolean awaitExit(long timeoutMs) throws InterruptedException {
        return exited.await(timeoutMs, TimeUnit.MILLISECONDS);
    }

    /** 端点配置文件路径。 */
    public Path configFile() {
        return configOut;
    }

    /** 探针声明（诊断用）。 */
    public ReadyProbe.Spec readySpec() {
        return ready;
    }

    /** 已写入的端点告知（内核 → SUT 方向，诊断用）。 */
    public Map<String, String> notifiedEndpoints() {
        return new LinkedHashMap<>(endpoints);
    }

    /**
     * 释放本次运行持有的资源。
     *
     * <p>{@code command} 非空（代起形态，D7 ①）时**销毁子进程**并关掉本侧的 stdin/stdout/stderr；
     * 进程生命周期随"持有句柄的一方"走——场景/宿主跑完必须由我们收摊，不能把 JVM 留在机器上。
     *
     * <p>attach 形态（{@code command} 为空，D7 ②）本进程从未持有子进程，这里**不动任何进程**，
     * 只做无操作返回：进程归用户（§7.3）。
     */
    @Override
    public void close() {
        Process p = process;
        if (p == null || command.isEmpty()) {
            return; // attach：内核不拥有进程，没得可释放
        }
        // 顺序不能反：Windows 上阻塞在管道读里的 `readLine()` 是同步 ReadFile，既不被
        // `Thread.interrupt()` 打断，也不被 `close()` 打断——而 `close()` 要拿的正是读线程
        // 握着的那把流锁，先关流会**永久卡在 FileDescriptor.close0**（实测 jstack：主线程停在
        // 该 native 帧，pump 线程仍停在 readBytes）。
        // 先 destroy()：管道对端消失，读线程自行返回，随后关流不再有竞争。
        p.destroy();
        closeQuietly(p.getOutputStream());
        closeQuietly(p.getInputStream());
        closeQuietly(p.getErrorStream());
    }

    private static void closeQuietly(java.io.Closeable c) {
        if (c == null) {
            return;
        }
        try {
            c.close();
        } catch (IOException e) {
            // 进程已退出时管道关闭会抛 IOException：属正常收尾，不是错误（§12 不静默的是
            // "被隐藏的失败结论"，不是"关闭已关闭的流"）
        }
    }
}
