package io.duo.sim.kernel.sut;

import io.duo.sim.kernel.api.ComponentException;
import io.duo.sim.kernel.api.Event;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

/**
 * external SUT 启动器（设计 §7.3，M6 交付物 1；决策 D7/D9 见 {@code docs/DECISIONS.md}）。
 *
 * <p><b>内核 → SUT 端点告知（主途径）</b>：生成端点配置文件（{@code launch.configOut}），
 * 写入 {@code duo.endpoint.<contract>=<endpoint>} 与节点 {@code config} 键值（{@code ready.*}
 * 是内核探针声明，不写入），并经环境变量 {@code duo.config} 把文件路径告知子进程。
 *
 * <p><b>SUT → 内核端点发现（兜底途径）</b>：解析子进程 stdout 中形如
 * {@code duo.endpoint.<contract>=<endpoint>} 的行（§7.3 行格式：**行首即前缀**，容忍首尾空白），
 * 记为「已发现端点」并发 {@code sim.external-endpoint} 事件（source=stdout）。
 * 注意：SUT 若把内核写入的配置行**原样回显**到 stdout，会被当作自身端点宣告——
 * 端点宣告行必须由 SUT 显式打印（设计约定）。
 *
 * <p><b>就绪</b>：轮询 {@link ReadyProbe}（tcp/http）至 {@code ready.timeout}；
 * 探针超时或 ready 前退出都归启动失败路径（§12），且**优先报「退出」根因**——
 * 进程已死时继续等探针超时会把根因掩盖成超时（与 in-process 的快速失败口径一致）。
 *
 * <p><b>生命周期归用户（§7.3）</b>：场景结束**不杀**进程（{@link #leftRunning()} 供调用方
 * 判定与提示，句柄经 {@link #process()} 暴露给用户自行终止）；但**启动失败**时销毁
 * （决策 D9：未就绪的子进程从未成为 SUT，留着必然泄漏）。
 */
public final class ExternalSutLauncher implements AutoCloseable {

    /** 探针轮询间隔。 */
    private static final long POLL_INTERVAL_MS = 200;
    /** 启动失败时等待子进程退出的宽限。 */
    private static final long KILL_TIMEOUT_MS = 5_000;
    /** 端点告知行的固定前缀（§7.3 行格式）。 */
    private static final String ENDPOINT_PREFIX = "duo.endpoint.";

    private final String sutId;
    private final List<String> command;
    private final Map<String, String> config;
    private final Map<String, String> endpoints;
    private final Consumer<Event> eventSink;
    private final Path configOut;
    private final ReadyProbe.Spec ready;
    private final Map<String, String> discovered = new ConcurrentHashMap<>();
    private final CountDownLatch exited = new CountDownLatch(1);
    private volatile Process process;
    private volatile boolean readyConfirmed;
    private volatile Integer exitCode;

    /**
     * @param command     空列表＝attach 形态（进程由用户自行启动，内核只写配置 + 探针就绪）
     * @param fallbackPort {@code ready.port} 缺省时的兜底端口（节点 exposes 首个非 0 端口）
     */
    public ExternalSutLauncher(String sutId, List<String> command, Map<String, String> config,
                               Map<String, String> endpoints, Consumer<Event> eventSink,
                               Path configOut, int fallbackPort) {
        this.sutId = sutId;
        this.command = List.copyOf(command);
        this.config = Map.copyOf(config);
        this.endpoints = Map.copyOf(endpoints);
        this.eventSink = eventSink;
        this.configOut = configOut;
        this.ready = ReadyProbe.spec(config, fallbackPort);
    }

    /**
     * 写端点配置文件 → （代起形态）拉起进程 → 轮询 ready。
     *
     * @throws ComponentException 探针超时 / ready 前退出 / 进程拉不起来
     */
    public void start() {
        writeConfigFile();
        if (!command.isEmpty()) {
            spawn();
        }
        try {
            awaitReady();
        } catch (RuntimeException e) {
            killProcess(); // D9：启动失败即销毁，不留孤儿 JVM
            throw e;
        }
        eventSink.accept(Event.sim("sim.external-sut-ready", sutId,
                Map.of("probe", ready.type(), "target", ready.describe(),
                        "attach", command.isEmpty())));
    }

    /** 端点配置文件内容（§7.3 主途径）：端点行 + 节点 config（剔除内核探针声明）。 */
    private void writeConfigFile() {
        if (configOut == null) {
            return;
        }
        try {
            if (configOut.getParent() != null) {
                Files.createDirectories(configOut.getParent());
            }
            try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(configOut,
                    StandardCharsets.UTF_8))) {
                pw.println("# generated by Duo — external SUT endpoint notification (§7.3)");
                endpoints.forEach((contract, addr) ->
                        pw.println(ENDPOINT_PREFIX + contract + "=" + addr));
                config.forEach((k, v) -> {
                    if (!k.startsWith("ready.")) {
                        pw.println(k + "=" + v);
                    }
                });
            }
        } catch (IOException e) {
            throw new ComponentException("cannot write external SUT config: " + configOut, e);
        }
    }

    private void spawn() {
        ProcessBuilder pb = new ProcessBuilder(command).redirectErrorStream(true);
        if (configOut != null) {
            pb.environment().put("duo.config", configOut.toAbsolutePath().toString());
        }
        try {
            process = pb.start();
        } catch (IOException e) {
            throw new ComponentException("cannot start external SUT process: "
                    + String.join(" ", command), e);
        }
        eventSink.accept(Event.sim("sim.external-process-started", sutId,
                Map.of("pid", process.pid(), "command", String.join(" ", command))));
        Thread.ofVirtual().name("duo-external-stdout-" + sutId).start(this::pumpStdout);
        Thread.ofVirtual().name("duo-external-exit-" + sutId).start(this::watchExit);
    }

    /** stdout 兜底途径：逐行找行首的 {@code duo.endpoint.<contract>=<endpoint>}（容忍首尾空白）。 */
    private void pumpStdout() {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(
                process.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parsed = parseEndpointLine(line);
                if (parsed == null) {
                    continue;
                }
                discovered.put(parsed[0], parsed[1]);
                eventSink.accept(Event.sim("sim.external-endpoint", sutId,
                        Map.of("contract", parsed[0], "endpoint", parsed[1],
                                "source", "stdout")));
            }
        } catch (IOException ignored) {
            // 进程退出即流关闭：属正常收尾，不是错误
        }
    }

    /**
     * 解析端点告知行（包级可见供单测）：返回 {@code [contract, endpoint]}，非端点行返回 null。
     * 行格式严格按 §7.3——**行首**即 {@code duo.endpoint.}（容忍首尾空白），避免把日志中
     * 引用的配置文本误判为端点宣告。
     */
    static String[] parseEndpointLine(String line) {
        if (line == null) {
            return null;
        }
        String trimmed = line.trim();
        if (!trimmed.startsWith(ENDPOINT_PREFIX)) {
            return null;
        }
        int eq = trimmed.indexOf('=');
        if (eq < 0) {
            return null;
        }
        String contract = trimmed.substring(ENDPOINT_PREFIX.length(), eq).trim();
        String endpoint = trimmed.substring(eq + 1).trim();
        if (contract.isEmpty() || endpoint.isEmpty()) {
            return null;
        }
        return new String[]{contract, endpoint};
    }

    private void watchExit() {
        int code;
        try {
            code = process.waitFor();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return;
        }
        exitCode = code;
        exited.countDown();
        if (!readyConfirmed) {
            return; // ready 前退出由 start() 的竞速判定报根因，不在此发事实事件
        }
        if (code == 0) {
            eventSink.accept(Event.sut("sut.exited", sutId, Map.of("exitCode", code)));
        } else {
            eventSink.accept(Event.sut("sut.crashed", sutId, Map.of("exitCode", code,
                    "error", "external process exited with code " + code)));
        }
    }

    private void awaitReady() {
        long deadline = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(ready.timeoutMs());
        while (true) {
            Process p = process;
            if (p != null && !p.isAlive()) {
                throw new ComponentException("external SUT exited before ready: " + sutId
                        + " (exit code " + exitValueOf(p) + ")");
            }
            if (ReadyProbe.once(ready)) {
                readyConfirmed = true;
                return;
            }
            if (System.nanoTime() >= deadline) {
                throw new ComponentException("external SUT ready timeout (" + ready.timeoutMs()
                        + "ms): " + sutId + " (probe " + ready.type() + " " + ready.describe() + ")");
            }
            try {
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new ComponentException("external SUT ready interrupted: " + sutId, e);
            }
        }
    }

    private int exitValueOf(Process p) {
        try {
            return p.exitValue();
        } catch (IllegalThreadStateException e) {
            Integer seen = exitCode;
            return seen == null ? -1 : seen;
        }
    }

    /** 启动失败路径的销毁（D9）：先 destroy，宽限内不退再 destroyForcibly。 */
    private void killProcess() {
        Process p = process;
        if (p == null) {
            return;
        }
        if (p.isAlive()) {
            p.destroy();
            try {
                if (!p.waitFor(KILL_TIMEOUT_MS, TimeUnit.MILLISECONDS)) {
                    p.destroyForcibly();
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                p.destroyForcibly();
            }
        }
        exited.countDown();
    }

    // ---- 观测面 ----

    /** 场景结束时进程是否仍在运行（§7.3：内核不杀，由调用方提示用户自行终止）。 */
    public boolean leftRunning() {
        Process p = process;
        return p != null && p.isAlive();
    }

    /** 子进程句柄（attach 形态为 null）；生命周期归用户，故公开供其终止。 */
    public Process process() {
        return process;
    }

    /** 子进程 pid（attach 形态为 null）。 */
    public Long pid() {
        Process p = process;
        return p == null ? null : p.pid();
    }

    /** stdout 兜底途径发现的端点（contract → endpoint）。 */
    public Map<String, String> discoveredEndpoints() {
        return Map.copyOf(discovered);
    }

    /** ready 是否已被探针确认。 */
    public boolean readyConfirmed() {
        return readyConfirmed;
    }

    /** 退出码（未退出为 null）。 */
    public Integer exitCode() {
        return exitCode;
    }

    /** 等待退出（供诊断/测试）。 */
    public boolean awaitExit(long timeoutMs) throws InterruptedException {
        return exited.await(timeoutMs, TimeUnit.MILLISECONDS);
    }

    /** 端点配置文件路径。 */
    public Path configFile() {
        return configOut;
    }

    /** 探针声明（诊断用）。 */
    public ReadyProbe.Spec readySpec() {
        return ready;
    }

    /** 已写入的端点告知（内核 → SUT 方向，诊断用）。 */
    public Map<String, String> notifiedEndpoints() {
        return new LinkedHashMap<>(endpoints);
    }

    /** 关闭＝不杀（设计 §7.3）；需要强制终止时调用方用 {@link #process()} 自行处置。 */
    @Override
    public void close() {
        // 故意为空：external SUT 生命周期归用户
    }
}
